import type { Metadata } from 'next'
import {
  Card,
  CardDescription,
  CardHeader,
  CardTitle,
} from '@/components/ui/card'
import FormSettings from './form'
import prisma from '@/lib/db'
import { getKindeServerSession } from '@kinde-oss/kinde-auth-nextjs/server'
import { unstable_noStore as noStore } from 'next/cache'
export const metadata: Metadata = {
  title: 'Use Pomodoro - Settings',
  description: 'Generated by create next app',
}

function getDataUser(userId: string) {
  noStore()
  const data = prisma.user.findUnique({
    where: {
      id: userId,
    },
    select: {
      name: true,
      email: true,
      colorScheme: true,
      timePomorodo: true,
      pausePomodoro: true,
      urlVideo: true,
    },
  })

  return data
}

export default async function Settings() {
  const { getUser } = getKindeServerSession()
  const user = await getUser()
  const data = await getDataUser(user?.id as string)

  return (
    <Card className="w-full xl:max-w-[80%]">
      <CardHeader>
        <CardTitle>Editar Configurações</CardTitle>
        <CardDescription>
          Edite novas configurações para seu dashboard em um clique.
        </CardDescription>
      </CardHeader>
      <FormSettings data={data} userId={user?.id as string} />
    </Card>
  )
}
